name: Windows - LiteManager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building
    runs-on: windows-latest

    steps:
      - name: Downloading & Installing Essentials
        shell: cmd
        run: |
          curl -L -o Downloads.bat "https://gitlab.com/chamod12/Im_win-10_github_rdp/-/raw/main/Downloads.bat"
          Downloads.bat

      - name: Connect to LiteManager
        shell: cmd
        run: show.bat

      - name: Time Counter
        shell: cmd
        run: loop.bat
